services:
  hazelcast:
    image: hazelcast/hazelcast
    pull_policy: missing
  management-center:
    image: hazelcast/management-center:5.3.3
    pull_policy: missing
    ports:
      - "8080:8080"
    environment:
      - MC_DEFAULT_CLUSTER=dev
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast
